name: build
on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build event service
        run: |
          cd ./event-service
          go build -v .
      - name: Build user service
        run: |
          cd ./user-service
          go build -v .
      - name: Build post service
        run: |
          cd ./post-service
          go build -v .